// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfAmTx2EA3qwOdWwO0tzntJF71p9q_cY',
    appId: '1:399225475600:web:bc899f6cf62d2d741f7095',
    messagingSenderId: '399225475600',
    projectId: 'routewise-ca56a',
    authDomain: 'routewise-ca56a.firebaseapp.com',
    storageBucket: 'routewise-ca56a.firebasestorage.app',
    measurementId: 'G-SVS5GHN6L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaI3IH_r9bk3o6RMf897MoQsDEgASUb_A',
    appId: '1:399225475600:android:c6ca3dc58cf0a0961f7095',
    messagingSenderId: '399225475600',
    projectId: 'routewise-ca56a',
    storageBucket: 'routewise-ca56a.firebasestorage.app',
  );
}
